### ISSUE TITLE
This broke my wifi.

### ISSUE THREAD

**Issue by nickthekidNL** [Lawin0129/LawinServer#10]
My computer crashed while using this. The crash was unrelated to the lawinserver. However, now I am unable to connect to the internet unless I have this running at all times...

**Comment by KappasDEV** [comment]
You probably already found a fix, but just incase:

- turn off your proxy’s
- reboot your router

hope I helped if it’s still happening :)

**Comment by nickthekidNL** [comment]
I did find a fix. Thanks. Funny enough installing and playing the new era
launcher fixed it. I guess because it uses same method.
