### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by TheJrEU** [Lawin0129/LawinServer#2]
hi im trying to get into og fortnite its sayin cant connect to servers ive downloaded the new lawin server but dont know how to redirect fortnite to 3551

**Comment by rhaym-tech** [comment]
Try to change port to 9999

**Comment by TheJrEU** [comment]
i cant because 9999 dont work. on the new lawin server it says port 3551, and in the (README.MD) file it says 'Use something to redirect the fortnite servers to localhost:3551 (Which could be fiddler, psychopasts custom lawinserver launcher, ssl bypass that redirects servers, etc...) but idk hwo to redirect it to  port 3551

**Comment by Leo-crypto1** [comment]
Have the exact same problem, ive been messing around with fiddler for the last 2 hours and still have no idea how to redirect the traffic from port 9999 to 3551.

**Comment by TheJrEU** [comment]
so did you manage to get into old fortnite ?

**Comment by Leo-crypto1** [comment]
No i sadly didnt
Actively working on finding out how to do it still

**Comment by bruh14574** [comment]
alright guys I think I might have found something to help up on our quest if you go to the search bar and look up proxy and go to proxy settings after launcher Lawin Server.exe you will see a option to use a proxy server it should be checked if its not restart lawin server.exe but it gives you an option to add the port so keep that in mind I am trying it right now get back to me when you see this

**Comment by Leo-crypto1** [comment]
Nah mate, that aint it

**Comment by bruh14574** [comment]
which file did you modify?

**Comment by Leo-crypto1** [comment]
index.js

**Comment by bruh14574** [comment]
I went to the new Lawin Server download:https://github.com/PsychoPast/LawinServer and went to Proxy and then proxy and changed the default port to 3551 but I also found this text

usage:
Double click the exe (uses default port: 9999) *RECOMMENDED*

Launch with arg: LawinServer.exe *port* (specifies the port to use. Keep in mind a port can be unavailable)

[Download Net core 3.1 Runtime](https://download.visualstudio.microsoft.com/download/pr/d97cfaf4-b17f-46c7-9a11-7f0d25dfd8b0/f76d4fce8e38b289efb9403aab0a0c9f/dotnet-runtime-3.1.5-win-x64.exe)

**Comment by bruh14574** [comment]
there are stars around port after lawin server.exe in the thing I sent above

**Comment by Leo-crypto1** [comment]
Did you try running it?

**Comment by bruh14574** [comment]
yes nothing changed after i set the port to 3551

**Comment by bruh14574** [comment]
I am going to recreat lawin servers website with the code
I will send you the website when ready and you will have to use the old fiddler method but it should be fine

**Comment by Leo-crypto1** [comment]
Im not sure what you mean but we should just try everything at this point lmao
Im gonna go sleep cya tmr

**Comment by ExtremelyLazyCat** [comment]
To fix this, I was able to use Fiddler.
Refer to the beginning of this video to set up Fiddler: https://www.youtube.com/watch?v=4-DJZ5AFOMo
But use this script:
```
import System;
import System.IO;
import System.Threading;
import System.Web;
import System.Windows.Forms;
import Fiddler;

class Handlers
{
    static function OnBeforeRequest(oSession: Session) {
        if (oSession.hostname.Contains(".ol.epicgames.com"))
        {
            if (oSession.HTTPMethodIs("CONNECT"))
            {
                // This is just a fake tunnel for CONNECT requests
                oSession["x-replywithtunnel"] = "FortniteTunnel";
                return;
            }

            oSession.fullUrl = "http://127.0.0.1:3551" + oSession.PathAndQuery;
        }
    }
}
```
Then try using launch.bat.

**Comment by TheJrEU** [comment]
this isnt working can you add my discord to explain to me its JrEU#6969

**Comment by TheJrEU** [comment]
NEVER mind its fixed

**Comment by ayayayayyayayayyayay** [comment]
> NEVER mind its fixed

so you can play polaris? if so how did you do this?

**Comment by Leo-crypto1** [comment]
He did what the aother guy said

**Comment by Leo-crypto1** [comment]
> To fix this, I was able to use Fiddler.
> Refer to the beginning of this video to set up Fiddler: https://www.youtube.com/watch?v=4-DJZ5AFOMo
> But use this script:
> 
> ```
> import System;
> import System.IO;
> import System.Threading;
> import System.Web;
> import System.Windows.Forms;
> import Fiddler;
> 
> class Handlers
> {
>     static function OnBeforeRequest(oSession: Session) {
>         if (oSession.hostname.Contains(".ol.epicgames.com"))
>         {
>             if (oSession.HTTPMethodIs("CONNECT"))
>             {
>                 // This is just a fake tunnel for CONNECT requests
>                 oSession["x-replywithtunnel"] = "FortniteTunnel";
>                 return;
>             }
> 
>             oSession.fullUrl = "http://127.0.0.1:3551" + oSession.PathAndQuery;
>         }
>     }
> }
> ```
> 
> Then try using launch.bat.
> Edit: Make sure to press Save Script
> Edit2: You can skip the AutoResponder Part in the video

Holy shit mate this worked! I love you

**Comment by ExtremelyLazyCat** [comment]
Full Tutorial: 
Follow instructions in README.md to setup server
Download Fiddler [here](https://www.telerik.com/download/fiddler/fiddler4) and proceed with the setup, then launch Fiddler.
Press Cancel to any prompts you may have when starting it up.
Go to Tools > Options.
![image](https://user-images.githubusercontent.com/41519857/104104956-6173fd80-5268-11eb-8f90-b40a5df91000.png)
Press HTTPS.
![image](https://user-images.githubusercontent.com/41519857/104104997-8ec0ab80-5268-11eb-9bab-bf98cfb5eec6.png)
Copy my settings.
![image](https://user-images.githubusercontent.com/41519857/104105130-684f4000-5269-11eb-920f-485d823fe7bb.png)
Press Actions and then press Trust Root Certificate
![image](https://user-images.githubusercontent.com/41519857/104105115-4e156200-5269-11eb-9ec2-7bc0072ebf23.png)
Press "Yes" to any prompts, then press OK at the end.
![image](https://user-images.githubusercontent.com/41519857/104105059-e828da80-5268-11eb-9cbf-bb15d8685f23.png)
![image](https://user-images.githubusercontent.com/41519857/104105080-07276c80-5269-11eb-8d33-64fbd4079779.png)
Press OK to exit out of the dialog then click "FiddlerScript".
![image](https://user-images.githubusercontent.com/41519857/104105387-eeb85180-526a-11eb-91f8-1f0ec32b4a09.png)
![image](https://user-images.githubusercontent.com/41519857/104105438-4f478e80-526b-11eb-819f-dab45bd55f8a.png)
Delete everything in the box and replace it with this script:
`import System;
import System.IO;
import System.Threading;
import System.Web;
import System.Windows.Forms;
import Fiddler;

class Handlers
{
    static function OnBeforeRequest(oSession: Session) {
        if (oSession.hostname.Contains(".ol.epicgames.com"))
        {
            if (oSession.HTTPMethodIs("CONNECT"))
            {
                // This is just a fake tunnel for CONNECT requests
                oSession["x-replywithtunnel"] = "FortniteTunnel";
                return;
            }

            oSession.fullUrl = "http://127.0.0.1:3551" + oSession.PathAndQuery;
        }
    }
}`
![image](https://user-images.githubusercontent.com/41519857/104105460-78681f00-526b-11eb-8670-27f242a2129b.png)
![image](https://user-images.githubusercontent.com/41519857/104105475-903fa300-526b-11eb-848a-e663e452f716.png)
Now press "Save Script"
![image](https://user-images.githubusercontent.com/41519857/104105486-afd6cb80-526b-11eb-8cbe-6a7b724442dc.png)
Now if you installed NodeJS and ran the install_packages.bat, open the start.bat in the LawinServer-main and you should be good to go!
![image](https://user-images.githubusercontent.com/41519857/104105541-1cea6100-526c-11eb-8dac-37e91ed46041.png)
Hmu on Discord @ Kataack#7628 if you have any questions.
Note for OP: Please close the issue on this question so we know its resolved.

**Comment by TheJrEU** [comment]
i added your discord woudl you be able to send me the newest polaris version please

**Comment by plamen6789official** [comment]
Why does it say: Fortnite Didn't Start Correctly, Start from the epic game l something like that.

**Comment by plamen6789official** [comment]
https://user-images.githubusercontent.com/77294971/104223631-8e810580-544c-11eb-8b65-fdc0800c7c8b.mp4

**Comment by Fischsalat** [comment]
Guys, just start it and then use this launcher (Aurora Launcher with changed URI in ssl bypass)

[Aurora Launcher for localhost.zip](https://github.com/Lawin0129/LawinServer/files/5860302/Aurora.Launcher.for.localhost.zip)

**Comment by SgtGigdi** [comment]
HELP ME

**Comment by rikuboi** [comment]
can u change the item shop

**Comment by jvgames-BR16** [comment]
hey, error on login i login and the error unable to login to fortnite server
