### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by TXDDANGER** [Lawin0129/LawinServer#3]
pls help how can i redirect the fortnite servers to localhost:3551

**Comment by Beat-YT** [comment]
Im gonna modify the LawinServer Proxy

**Comment by TXDDANGER** [comment]
What do you mean?

**Comment by Beat-YT** [comment]
A redirecter

**Comment by TXDDANGER** [comment]
Can you send me?

**Comment by Beat-YT** [comment]
Not Yet

**Comment by TXDDANGER** [comment]
Why not yet?

**Comment by Beat-YT** [comment]
Not done

**Comment by Beat-YT** [comment]
[LocalLauncher.zip](https://github.com/Lawin0129/LawinServer/files/5810168/LocalLauncher.zip)

**Comment by TXDDANGER** [comment]
I cant open the exe file why

**Comment by TXDDANGER** [comment]
Pls help

**Comment by Ussy395** [comment]
yes i open the exe file then it doesnt do anything

**Comment by TXDDANGER** [comment]
I have fixed the Problem

**Comment by TXDDANGER** [comment]
You must copy all lawin dll to the exe file

**Comment by MidasLeaks** [comment]
WELL NO SHIT
