### ISSUE TITLE
New Fortnite Versions just wont work

### ISSUE THREAD

**Issue by ye01011001** [Lawin0129/LawinServer#80]
I can play Season 1-3 without problems and even buy the battle pass but Season 6 just gives a "Fortnite isnt Correctly Started" Error and Season 20 Gives a Red "Cant Connect Screen", pls help.

Here is my Launch script:
FortniteClient-Win64-Shipping.exe -skippatchcheck -AUTH_LOGIN=unused -AUTH_PASSWORD=f624593b31474caa9e0fd63c4443d6b4 -AUTH_TYPE=exchangecode -epicapp=Fortnite -epicenv=Prod -EpicPortal -useallavaliblecores -HTTP=WinINet -NOSSLPINNING -steamimportavailable -epicusername=ye_ -epicuserid= -epiclocale=en -epicsandboxid=fn
Is something with my Launch script wrong or my LawinServer?

Here is a screenshot on Season 20: (its German but basically it cant connect to epic services)
![image](https://user-images.githubusercontent.com/51487454/173363234-cf67f588-efe9-4ca5-b9ee-e15700dcc4b4.png)

**Comment by ye01011001** [comment]
and yes i am using Fiddler and using the FiddlerScript

**Comment by Milxnor** [comment]
You can’t launch Fortnite like that for newer versions. In like s5+ you need a ssl bypass, and in s9+ I think you need an fltoken, and then in like s18+ you need a caldera and fltoken.

**Comment by ye01011001** [comment]
ok, btw for 14.60 i already fixed it so how can i fix efven never versions?
