### ISSUE TITLE
Help for changing item shop items

### ISSUE THREAD

**Issue by AntogamerYT** [Lawin0129/LawinServer#86]
Hi, I was trying to change the item shop items but came into an issue: on the [catalog_config.json](https://github.com/Lawin0129/LawinServer/blob/main/Config/catalog_config.json) I don't know what to put, can someone tell me what do I have to put?

**Comment by juhaszbalazs2005** [comment]
Hello! It won't work even if you write items in it, i tried

**Comment by LoigiTV** [comment]
Use LawinServerV2

**Comment by AntogamerYT** [comment]
> Use LawinServerV2

bro.. this is months old, why even bother replying
