### ISSUE TITLE
Party Problems

### ISSUE THREAD

**Issue by Repressoh** [Lawin0129/LawinServer#91]
So, basically i have 2 clients connected to the lawin server. When I invite one to the party, Both can click accept but nothing more happens. When i try to join the party for the second time, he says its still joining. Some help?

![image](https://user-images.githubusercontent.com/85702320/195632348-68626197-cce9-4789-8c30-a27d20a05a3d.png)

**Comment by PRO100KatYT** [comment]
Parties aren't a feature in the localhosted LawinServer XMPP... yet 👀

Currently it's only possible in the one hosted on heroku by Lawin you can connect to.

**Comment by AntogamerYT** [comment]
@PRO100KatYT didn't lawin shut down the heroku lawinserver?

**Comment by PRO100KatYT** [comment]
Hmm looks like it just stopped working a few hours ago.

**Comment by Repressoh** [comment]
> Parties aren't a feature in the localhosted LawinServer XMPP... yet 👀
> 
> Currently it's only possible in the one hosted on heroku by Lawin you can connect to.

I know it's an annoying question, but Is there an ETA for the release of this feature for localhost?

**Comment by PRO100KatYT** [comment]
[It's ready : )](https://github.com/Lawin0129/LawinServerV2)

**Comment by Repressoh** [comment]
> [It's ready : )](https://github.com/Lawin0129/LawinServerV2)

Thanks!
