### ISSUE TITLE
Not working on latest (current ver. 22.30)

### ISSUE THREAD

**Issue by TeoVR-YT** [Lawin0129/LawinServer#93]
![Screenshot 2022-11-01 23-46-37](https://user-images.githubusercontent.com/106691854/199839485-34517dd5-b738-4f94-940b-c7d4e002e27d.png)

**Comment by PRO100KatYT** [comment]
what launcher are you using?

**Comment by TeoVR-YT** [comment]
> what launcher are you using?

The NEW Carbon launcher!

**Comment by PRO100KatYT** [comment]
Fixed it. Currently you can find it on [my fork](https://github.com/PRO100KatYT/LawinServer-1). I'll open a PR here later.

**Comment by TeoVR-YT** [comment]
> Fixed it. Currently you can find it on [my fork](https://github.com/PRO100KatYT/LawinServer-1). I'll open a PR here later.

Thank you!

**Comment by PRO100KatYT** [comment]
It's now merged here too.
